IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'DESKTOP-12RJGNS\Bev')
CREATE LOGIN [DESKTOP-12RJGNS\Bev] FROM WINDOWS
GO
CREATE USER [DESKTOP-12RJGNS\Bev] FOR LOGIN [DESKTOP-12RJGNS\Bev]
GO
GRANT CONNECT REPLICATION TO [DESKTOP-12RJGNS\Bev]
