//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int product_id { get; set; }
        [Required(ErrorMessage ="*Product Name Required")]
        public string product_name { get; set; }
        [Required(ErrorMessage = "*Brand Required")]
        public string prodyct_brand { get; set; }
    }
}
