sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: PL9VtmtQsV0kOWE61Zl7O7elrcf1Rrvn0C5aIkeLAnVH94rZPKVXhz/KnScnqjjt+7yGsHdYL+0Lic6WgFei+Q19DKBpXsJ1Rkx7O98wxZxeGIZrP3tknnRHxcj6AJATst9h8lphw8J9aVwMSTCEDdCNbx4YjSfRWAflo3mT4De0VBrZrHz7vZ83XbOIsXtJMLo6UelEe+z8xhQy+qS5nrypBGEY1/Z8iAZR+kDaF1hp3tuzVUPRt87kVEo03RlyxEMNe7c9Q6Sodr0IJOLHl/z3Td7nK+g31xARUl7BNRHw5lKjNU6yEb3R4DEn83X0ljr7+4F9TbGTv0au9taotsnrImv/ciUpyBnPwD7eo2iU+7eQuEq4R9wfNtGUD/5USm0ElYeaV0UVGfEpIIb64o41xvlcZYN/8ZONOMwUXmStssfjbN1bc2yvEEQrMmgSA+ba44fpZB3gJXmoSxiG9xgudLFiXCmi0Q6lMHR53O8Zm+Gi0YgFeyvBsk5PiMQL78Tsnrf+mj7V8UUY8Xmz+hNhLC//HbmDF9F+X9cAhrlOVwRz75/0Nc3sc/YXIIU7PCkvQXewu+hjGkxlWlpjMkYOTXV07IHMZf4fW625Y+yJcML3z5s07/rmVJfHF83fZ5U620X9pOZSemm/puw4mb286HmPDLhIqrEtYM2FzuY=
  - secure: YQc+VJSXN2FkDVuTb3gEDdBUf18zbOT9mA8B3IY+VOy3t33T1Fq4id92qPgOgcBriyjhzcJcwNQ1GSsmjofVci0h9cx0ltgnjU/t7X7AAAI95OZO2brawuH7w8ghdypuUM7A6iyPI5oy4JRwmRBfuKxiz+Tk8OOGBVkp3e04ynLOQZzxYVife8BOEpMx0eNUA/8VYPxOnspnqU+lKayrwaZU+nOG7uHz1dBoyom+wlWrh+78GiD4bYdzo/ftSAWvzYraeLbtmggjRAYKGMEBfIPG3NabX3DgvqB3xKujjHEhAG/MFfu8fTs4Z/jfrDlzDcoZ62L0vQ80fuEznoJciH4J53QeTooVdinp7gF43AaCyOpN9jJcdBCdoQN6HK2MVBuL3NlBX7ed5MFSbekr9/AF5ffYuIyrB5gEJKaIBiFIawgnpad7nJBzQT+21+p+t05cJXPqmuXTm+3LbKDBMhKXOXygcIBPVPcGCkGmS03Q2psNMOuXk8OMOXjW0BAYyW0kEWMs4/P+Gjy7mKHEXeyGaKVP1pWkrZsBragrnzzTpRcJNQyovUIAgMbScB7K1KtDpntfc0kzu+O46CfspGIdwOlfhzn5kHfzqJDldMe7PjtIOIev1HgYwL7DbVNxU0iFXEoDgJZGeiRYqe32ad7Z/RF9pj5qvKqq7pAJspM=
  - secure: i2P5Q2pc2j8pQchdQv/S7LeczZFtauLNT2VOWzstmobcEsW1K2pxohWMeLSGNvtu7ONZTz63Ix+0142etn4veq7R57KBPs9QSn+pJa1S3wUy6E/AhLZCSi6nQNrET6a63+7aIP8rH1oqiTqpiD8PX7YPp8ZEHq8bKsF+w9pRmZg2y6ad8ZihQ3A9zyV678Qe2GTEK6Hak2ODwVN/3bcvLB+Tgsj+OSkAg3dAKLMHGmM2Pd4ePXmDXu51yVGSgf0AlWofEmV3GNZjSAKziob1wcyzKTuIUaKhrbnOKJQDAOg9FC2FnLb1GSln6ZFI5eFOKEeCks9SOddk7prdTIdGltPoduXVQk4RwkLzkZVPhSS1GFy02t+w4cqMCAlniYxK+TrTv0muKcKFbtKQVtENVj8RaHau9s1PjIoGs0al8GRVFJodhN/Da+xXhmivw5i/KjXrjXO5hJLNEjbVr02pPVXFuRG6MP3cTZ1u3CE5+An7MgWX3XTHRjLp0ivduQ//b0eYDiAyQW8Rlc6skSYYrbI3h3Ow7fua5KdctLL8PZcUJDRO+iLb5pai7BpBol0q/jXHbM1uGqhQha4h9JvaNY34BqJD1NwH+0gHK8gGD5r+dKCS9wsRLRb86puA+B7Xfrot18/XK7HDsnNZSz/1xEvleRP8cS5kuKzRkHB6rpI=
